on:
  schedule:
    # runs every day at 10:00 AM UTC in jan, feb, aug-dec
    - cron:  '0 10 * 1,2,9-12 *'
  workflow_dispatch:

name: update-computed-numbers

jobs:
  update:
    name: Update Computed Numbers
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            local::.,
            callr
          extra-packages: nflverse/nflverse-data

      - name: Run update script
        run: Rscript -e 'source("data-raw/_save_computed_numbers.R")'
